### ISSUE TITLE
Storage: handle exceptions when reading wrong file type

### ISSUE THREAD

**Issue by dq-dx** [cs2103jan2016-f14-4j/main#102]
This is what happens when trying to read HashMap\<String, Integer\> from JSON, but the JSON file is actually a UserTagDatabase.

`Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected an int but was BEGIN_ARRAY at line 1 column 14 path $.
	at com.google.gson.Gson.fromJson(Gson.java:891)
	at com.google.gson.Gson.fromJson(Gson.java:844)
	at taskey.storage.Storage.readFromFile(Storage.java:127)
	at taskey.storage.Storage.loadTags(Storage.java:292)
	at taskey.storage.Storage.main(Storage.java:48)
Caused by: java.lang.IllegalStateException: Expected an int but was BEGIN_ARRAY at line 1 column 14 path $.
	at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1194)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:247)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:239)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:879)
	... 4 more`

**Comment by dq-dx** [comment]
Issue has cropped up again after changing the hashmap into an arraylist of tags.

**Comment by dq-dx** [comment]
Closing this issue as it falls under the purview of #220
